### ISSUE TITLE
Polite request - Build for Python 3.10?

### ISSUE THREAD

**Issue by storesund** [messense/fasttext-wheel#3]
Hi! I love the convenience of using your wheels when installing FastText, so first of all thank you for bothering to set this up. As we are slowly migrating to Python 3.10, I've seen that the builds for this Python version has failed here in GitHub actions. I don't have the full competency to do this myself - could you @messense in any way find time to correct those builds?

I would be really grateful. Thanks again.

**Comment by messense** [comment]
Done.
